
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgiztjpodhpqnmphctul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnaXp0anBvZGhwcW5tcGhjdHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NDQ3NzAsImV4cCI6MjA2MDQyMDc3MH0.fnAqdmXIIUMiUuztLNAuSAZBgpHDatZdFQYrvHRMmjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    headers: {
      'X-Client-Info': 'chef-saudavel-app'
    }
  }
});
